<a href="https://colab.research.google.com/github/parreira01/python/blob/master/M%C3%B3dulo3PacotesNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Vídeo 25: Outros pacotes do Python: NumPy - Matriz e Array


In [ ]:
import numpy as np

In [ ]:
# criando uma função da matriz linha
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
# criando um objeto como resultado da função da matriz linha
matriz_linha = np.array([1, 2, 3, 4, 5, 6])


In [ ]:
matriz_linha # A matriz linha mostra 1 linha com 5 colunas

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Apresentando um formato de 5 linhas e 1 coluna, o reshape é responsável por essa mudança começando por linhas e seguido por colunas.
vetor = matriz_linha.reshape(6,1)
vetor

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
# Criando valores para cada linha
matriz = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[100,200,300], [20,30,40]])
matriz

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12],
       [100, 200, 300],
       [ 20,  30,  40]])

In [ ]:
matriz[:, -1] # ':' todas as linhas e '-1' últimas colunas

array([  3,   6,   9,  12, 300,  40])

In [ ]:
matriz[3, :] # linha 3, todas as colunas

array([10, 11, 12])

In [ ]:
matriz[4, 1] # linha 4, posição 1 da coluna

200

In [ ]:
array = np.array( [ [[1,2], [5,6]], [[7,8],[88, 99]]]) # As matrizes são os colchetes de dentro que formam o array que é amontagem geral.
array

array([[[ 1,  2],
        [ 5,  6]],

       [[ 7,  8],
        [88, 99]]])

In [ ]:
# O 1º colchete [0] do array, aponta a 1ª matriz '[1,2], [5,6]', como sendo a posição da linha.
# O 2º colchete [1,0] do array, aponta a 1ª matriz '[1,2], [5,6]' como a posição da coluna, onde 1 é a 2ª linha [5,6] da coluna e 0 é a 1ª coluna da 2ª coluna[5].
array[0][1,0]

5

___
## Vídeo 26: Outros pacotes do Python: NumPy - Matriz de zeros e Dataframe

##### o NumPy é utilizado para cálculos de álgebra linear.








In [ ]:
matriz_zeros = np.zeros(shape = (12,1))
matriz_zeros

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
import pandas as pd


In [ ]:
# criando um data frame de zeros
# a vantagem de se trabalhar com esse formato de array(matriz) está na utilização de parte das informações pré definidas de um banco dados.
df = pd.DataFrame(data = matriz_zeros, columns = ['valores'])
df

valores
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0

In [ ]:
# criando um matriz identidade para realização de outros cálculos
matriz_identidade = np.eye(2)
matriz_identidade

array([[1., 0.],
       [0., 1.]])

___
## Vídeo 27: Outros pacotes do Python: NumPy - Valores aleatórios


In [ ]:
# criando matrizes, vetores ou matrizes-linhas com valores aleatórios
# todas as vezes que aplicar o objeto abaixo será gerado um novo valor aleatório
np.random.rand(2,2)

array([[0.6654968 , 0.84614963],
       [0.99315403, 0.85635919]])

In [ ]:
# adquirindo um mesmo valor aleatório para ser replicado
np.random.seed(0) # 0 para não haver alteração do valor aleatório
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [ ]:
# para testes com valores aleatórios
dist_normal = np.random.normal (loc= 1, scale= 2, size= (6, 3))

In [ ]:
dist_normal

array([[ 1.28808714,  3.90854701,  2.52207545],
       [ 1.24335003,  1.88772647,  1.66734865],
       [ 3.98815815,  0.58968347,  1.6261354 ],
       [-0.70819148, -4.10597963,  2.30723719],
       [ 2.7288724 , -0.48433004,  5.53950925],
       [-1.90873135,  1.09151703,  0.6256323 ]])

___
## Vídeo 28: Outros pacotes do Python: NumPy - Operações Matemáticas


In [ ]:
matriz_1 = np.array([[1,2],[3,4]])
matriz_2 = np.array([[5,6],[7,8]])

In [ ]:
matriz_1

array([[1, 2],
       [3, 4]])

In [ ]:
matriz_2

array([[5, 6],
       [7, 8]])

In [ ]:
np.add(matriz_1, matriz_2)

array([[ 6,  8],
       [10, 12]])

In [ ]:
np.subtract(matriz_1, matriz_2)

array([[-4, -4],
       [-4, -4]])

In [ ]:
np.divide(matriz_1, matriz_2)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
np.multiply(matriz_1, matriz_2) # faz multiplicação dos itens de cada matriz

array([[ 5, 12],
       [21, 32]])

In [ ]:
np.dot(matriz_1, matriz_2) # faz multiplicação de matrizes

array([[19, 22],
       [43, 50]])

In [ ]:
# somando os valores de uma matriz
np.sum(matriz_1)

10

In [ ]:
np.sum(matriz_1, axis=0) # soma os valores das colunas

array([4, 6])

In [ ]:
np.sum(matriz_1, axis=1) # soma os valores da linhas

array([3, 7])

___
## Vídeo 29: Outros pacotes do Python: NumPy - Algebra Linear
#### Transposta, Inversa e Solução de Equação
___



In [ ]:
matriz_1

array([[1, 2],
       [3, 4]])

In [ ]:
matriz_1.T # Transposta: a 1ª linha vira 1ª coluna e a 2ª linha vira 2ª coluna

array([[1, 3],
       [2, 4]])

In [ ]:
np.linalg.inv(matriz_1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

$3x_{0} + x_{1} = 9$\
$x_{0} + 2x_{1} = 8$
###### escrito em LaTex

In [ ]:
equacoes = np.array([[3,1],[1,2]])

In [ ]:
equacoes

array([[3, 1],
       [1, 2]])

In [ ]:
igualdade = np.array([[9],[8]])
igualdade

array([[9],
       [8]])

In [ ]:
solucao = np.linalg.solve(equacoes, igualdade)
solucao

array([[2.],
       [3.]])

In [ ]:
np.dot(equacoes, solucao)

array([[9.],
       [8.]])

___
## Vídeo 30, 31 e 32: Outros pacotes do Python: Sidrapy - Introdução SIDRA - Função Get_table


##### É um pacote de recuperação de dados do Banco de Dados do IBGE
##### Instalando o SIDRAPY

In [ ]:
pip install sidrapy


In [ ]:
import sidrapy as sdpy

In [ ]:
sdpy.get_table(table_code= '7061',territorial_level= '1', ibge_territorial_code= '1',
               variable= '306', classification= '315/7169')

NC                 NN                          MC  \
0  Nível Territorial (Código)  Nível Territorial  Unidade de Medida (Código)   
1                           1             Brasil                           2   

                  MN      V              D1C     D1N                D2C  \
0  Unidade de Medida  Valor  Brasil (Código)  Brasil  Variável (Código)   
1                  %   0.30                1  Brasil                306   

                                      D2N  \
0                                Variável   
1  IPCA dessazonalizado - Variação mensal   

                                               D3C  \
0  Geral, grupo, subgrupo, item e subitem (Código)   
1                                             7169   

                                      D3N           D4C          D4N  
0  Geral, grupo, subgrupo, item e subitem  Mês (Código)          Mês  
1                            Índice geral        202308  agosto 2023

In [ ]:
IPCA = sdpy.get_table(table_code= '7061',territorial_level= '1', ibge_territorial_code= '1',
               variable= '306', classification= '315/7169')

IPCA

NC                 NN                          MC  \
0  Nível Territorial (Código)  Nível Territorial  Unidade de Medida (Código)   
1                           1             Brasil                           2   

                  MN      V              D1C     D1N                D2C  \
0  Unidade de Medida  Valor  Brasil (Código)  Brasil  Variável (Código)   
1                  %   0.30                1  Brasil                306   

                                      D2N  \
0                                Variável   
1  IPCA dessazonalizado - Variação mensal   

                                               D3C  \
0  Geral, grupo, subgrupo, item e subitem (Código)   
1                                             7169   

                                      D3N           D4C          D4N  
0  Geral, grupo, subgrupo, item e subitem  Mês (Código)          Mês  
1                            Índice geral        202308  agosto 2023

In [ ]:
IPCA_2020 = sdpy.get_table(table_code= '7061',territorial_level= '1', ibge_territorial_code= '1',
               variable= '306', classification= '315/7169', period= 'all' )
IPCA_2020

NC                 NN                          MC  \
0   Nível Territorial (Código)  Nível Territorial  Unidade de Medida (Código)   
1                            1             Brasil                           2   
2                            1             Brasil                           2   
3                            1             Brasil                           2   
4                            1             Brasil                           2   
5                            1             Brasil                           2   
6                            1             Brasil                           2   
7                            1             Brasil                           2   
8                            1             Brasil                           2   
9                            1             Brasil                           2   
10                           1             Brasil                           2   
11                           1             Brasil                           2   
12                           1             Brasil                           2   
13                           1             Brasil                           2   
14                           1             Brasil                           2   
15                           1             Brasil                           2   
16                           1             Brasil                           2   
17                           1             Brasil                           2   
18                           1             Brasil                           2   
19                           1             Brasil                           2   
20                           1             Brasil                           2   
21                           1             Brasil                           2   
22                           1             Brasil                           2   
23                           1             Brasil                           2   
24                           1             Brasil                           2   
25                           1             Brasil                           2   
26                           1             Brasil                           2   
27                           1             Brasil                           2   
28                           1             Brasil                           2   
29                           1             Brasil                           2   
30                           1             Brasil                           2   
31                           1             Brasil                           2   
32                           1             Brasil                           2   
33                           1             Brasil                           2   
34                           1             Brasil                           2   
35                           1             Brasil                           2   
36                           1             Brasil                           2   
37                           1             Brasil                           2   
38                           1             Brasil                           2   
39                           1             Brasil                           2   
40                           1             Brasil                           2   
41                           1             Brasil                           2   
42                           1             Brasil                           2   
43                           1             Brasil                           2   
44                           1             Brasil                           2   

                   MN      V              D1C     D1N           D2C  \
0   Unidade de Medida  Valor  Brasil (Código)  Brasil  Mês (Código)   
1                   %   0.15                1  Brasil        202001   
2                   %   0.26                1  Brasil        202002   
3                

#### Os documentos do pacote Sidrapay estão no site sidrapay.ibge.gov.br