# Curso de Introdução ao Python: Módulo 3

---

<center>
<img src="https://github.com/marcelorandolfo/data-science/raw/master/images/imagem_curso.png" width="3000"/>
</center>


**Marcelo Randolfo** \\
**Fundação João Pinheiro**

---
## Outros pacotes úteis do Python

Atualmente existem mais de 240 mil pacotes implementados na linguagem Python e publicados no Python Package Index, [PyPI](https://pypi.org/). Sem dúvidas o mais utilizado entre eles é o pacote pandas, visto no módulo anterior, mas há outros pacotes bastante úteis também.

Neste módulo vamos observar quatro deles: [math](https://docs.python.org/3/library/math.html), [statistics](https://docs.python.org/3/library/statistics.html), [numpy](https://numpy.org/) e [sidrapy](https://pypi.org/project/sidrapy/).

---

### Pacote math

O pacote math disponibiliza diversas funções de cálculos matemáticos como raiz quadrada, exponencial, logaritmo, fatorial, além de funções de ajuste de valores. O pacote math também disponibiliza ao usuário valores de constantes mais utilizadas como *pi* e logaritmo natural (*e*).

O primeiro passo para utilizar o pacote é importá-lo para o ambiente Python do notebook. 

In [ ]:
# importando o pacote math
import math

In [ ]:
# obtendo os valores das constantes
print('Pi: {}'.format(math.pi))
print('Logaritmo natural: {}'.format(math.e))

Pi: 3.141592653589793
Logaritmo natural: 2.718281828459045


In [ ]:
# transformando os valores com o pacote math
pi_floor = math.floor(math.pi)
print('Valor de pi arredondado para baixo: {}'.format(pi_floor))

Valor de pi arredondado para baixo: 3


In [ ]:
# transformando os valores com o pacote math
pi_ceil = math.ceil(math.pi)
print('Valor de pi arredondado para cima: {}'.format(pi_ceil))

Valor de pi arredondado para cima: 4


In [ ]:
# transformando os valores (função round não é do pacote math)
pi_round = round(math.pi, 5)
print('Valor de pi com 5 casas decimais: {}'.format(pi_round))

Valor de pi com 5 casas decimais: 3.14159


In [ ]:
# cálculos com a função math - raiz quadrada
valor = 36
print('Raiz quadrada: {}'.format(math.sqrt(valor)))

Raiz quadrada: 6.0


In [ ]:
# cálculos com a função math - logaritmo
valor = 180
print('Logaritmo: {}'.format(math.log(valor)))

Logaritmo: 5.19295685089021


In [ ]:
# cálculos com a função math - logaritmo na base 10
valor = 180
print('Logaritmo: {}'.format(math.log10(valor)))

Logaritmo: 2.255272505103306


In [ ]:
# cálculos com a função math - potenciação
valor_a = 25
valor_b = 10
print('Valor de a elevado ao valor de b: {}'.format(math.pow(valor_a,valor_b)))

Valor de a elevado ao valor de b: 95367431640625.0


In [ ]:
valor_a ** valor_b

95367431640625

In [ ]:
# criando uma lista
lista = [25, 23, 28, 30, 28, 18, 31, 'Ausente', 27, 30]
print(lista)

[25, 23, 28, 30, 28, 18, 31, 'Ausente', 27, 30]


In [ ]:
# acessando o index do valor ausente
lista[-3]

'Ausente'

In [ ]:
# substituindo o valor ausente
lista[-3] = math.nan
print(lista)

[25, 23, 28, 30, 28, 18, 31, nan, 27, 30]


---

### Pacote statistics

Por sua vez,  o pacote `statistics` disponibiliza funções para cálculo de métricas estatísticas, como média, mediana, desvio padrão, variância. 

*Importante*: algumas funções do pacote statistics estão também implementadas no pacote pandas. Então se o usuário estiver trabalhando com dados de um Dataframe e quiser calcular estatísticas mais simples como média ou desvio padrão, o próprio pacote pandas já oferece essas funções, tornando dispensável o uso do pacote statistics. 

Porém, se o usuário estiver trabalhando com dados em formatos de listas ou tuplas ou quiser calcular estatísticas mais complexas como média harmônica e variância/desvio padrão populacionais, o pacote statistics é mais indicado.

In [ ]:
# importando o pacote statistics
import statistics as st

In [ ]:
# criando uma lista com dados
lista = [1, 5, 9, 11, 18, 20, 21, 35, 47, 47]
lista

[1, 5, 9, 11, 18, 20, 21, 35, 47, 47]

In [ ]:
# calculando a média
st.mean(lista)

21.4

In [ ]:
# salvando o resultado em um objeto
media = st.mean(lista)

In [ ]:
# calculando a mediana
mediana = st.median(lista)
mediana

19.0

In [ ]:
# calculando a mediana baixa
mediana_baixa = st.median_low(lista)
mediana_baixa

18

In [ ]:
# calculando a mediana alta
mediana_alta = st.median_high(lista)
mediana_alta

20

In [ ]:
# calculando a media harmônica
media_harmonica = st.harmonic_mean(lista)
media_harmonica

6.148853567575374

In [ ]:
# calculando a variância amostral e populacional
var_amostral = st.variance(lista)
var_populacional = st.pvariance(lista)

# observando valores
print('Variância amostral: {}'.format(var_amostral))
print('Variância populacional: {}'.format(var_populacional))

Variância amostral: 272.93333333333334
Variância populacional: 245.64000000000001


In [ ]:
# calculando o desvio padrão amostral e populacional
std_amostral = st.stdev(lista)
std_populacional = st.pstdev(lista)

# observando valores
print('Desvio padrão amostral: {}'.format(std_amostral))
print('Desvio padrão populacional: {}'.format(std_populacional))

Desvio padrão amostral: 16.520694093570444
Desvio padrão populacional: 15.672906558772052


In [ ]:
# conferindo resultados
print('Desvio padrão por meio da raiz quadrada da variância amostral: {}'.format(math.sqrt(var_amostral)))
print('Desvio padrão por meio da raiz quadrada da variância populacional: {}'.format(math.sqrt(var_populacional)))

Desvio padrão por meio da raiz quadrada da variância amostral: 16.520694093570444
Desvio padrão por meio da raiz quadrada da variância populacional: 15.672906558772052


---

### Pacote numpy

O pacote numpy é utilizado na programação Python para realizar cálculos matemáticos utilizando arranjos, vetores, matrizes e arrays (que são matrizes de N dimensões em conjunto). O pacote se assemelha em poder computacional com o software **Matlab**, mas com a legibilidade da linguagem Python.

Dentre os objetos do numpy destacam-se:
  * Objeto matriz: que permite o uso de funções relacionadas a algebra linear.
  * Objeto array: que permite o cálculo com objetos multidimensionais (muito utilizado em aplicações de *Machine Learning*).

Além do destaque aos objetos próprios do pacote, com o numpy também é possível gerar números aleatórios ou séries derivadas de uma distribuição de probabilidade qualquer. 

Para utilizar as funções do numpy precisamos primeiro importá-lo.

In [ ]:
# importando o pacote numpy
import numpy as np

In [ ]:
# criando um array de uma dimensão (matriz-linha)
matriz_linha = np.array([1, 2, 3, 4, 5]) 
matriz_linha

array([1, 2, 3, 4, 5])

In [ ]:
# obtendo a dimensão dessa matriz-linha
print(matriz_linha.shape)

(5,)


In [ ]:
# obtendo um vetor por meio da matriz-linha
vetor = matriz_linha.reshape(5,1)
vetor

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# criando um array de mais de uma dimensão 
matriz = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]) 
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# obtendo a primeira linha da matriz
linha_0 = matriz[0,:]
linha_0

array([1, 2, 3, 4, 5])

In [ ]:
# obtendo a última coluna
ultima_coluna = matriz[:,-1]
ultima_coluna

array([ 5, 10, 15])

In [ ]:
# obtendo o valor da segunda linha e da terceira coluna
valor_1_2 = matriz[1,2]
valor_1_2

8

In [ ]:
# alterando o valor da segunda linha e da terceira coluna
matriz[1,2] = 0
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  0,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# obtendo as duas últimas colunas das primeiras duas linhas
fatia_matriz = matriz[0:2,-2:]
fatia_matriz

array([[ 4,  5],
       [ 9, 10]])

In [ ]:
# criando um array
novo_array = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]] , 
                      [[16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 27, 28, 29]]])
novo_array

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 27, 28, 29]]])

In [ ]:
# obtendo a primeira matriz do array
novo_array[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# obtendo a segunda matriz do array
novo_array[1]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 27, 28, 29]])

In [ ]:
# obtendo a última linha da segunda matriz do array
novo_array[1,-1,:]

array([26, 27, 27, 28, 29])

In [ ]:
# obtendo a segunda coluna da primeira matriz do array
novo_array[0,:,1]

array([ 2,  7, 12])

In [ ]:
# utilizando operadores
matriz > 6

array([[False, False, False, False, False],
       [False,  True, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
# utilizando operadores
matriz == 0

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False]])

In [ ]:
# criando uma matriz 2 x 2 de zeros
matriz_zeros = np.zeros(shape = (2,2))   
matriz_zeros

array([[0., 0.],
       [0., 0.]])

In [ ]:
# criando uma coluna com 12 linhas de zeros
coluna_zeros = np.zeros(shape = (12,1))   
coluna_zeros

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
# integração com o pandas
import pandas as pd
df = pd.DataFrame(data = coluna_zeros, columns = ['Valores'])
df

Valores
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0

In [ ]:
# criando uma matriz 2x2 com uma constante
constante = 5
matriz_constante = np.full(shape =  (2,2), fill_value = constante)  
matriz_constante

array([[5, 5],
       [5, 5]])

In [ ]:
# integração com o pandas
df_5 = pd.DataFrame(data = matriz_constante, columns=['Coluna 1','Coluna 2'])
df_5

Coluna 1  Coluna 2
0         5         5
1         5         5

In [ ]:
# criando uma matriz identidade 2x2
matriz_identidade = np.eye(2)
matriz_identidade

array([[1., 0.],
       [0., 1.]])

In [ ]:
# criando uma matriz identidade 3x3
matriz_identidade_3x3 = np.eye(3)
matriz_identidade_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Valores aleatórios

[**Link**](https://docs.scipy.org/doc//numpy-1.12.0/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState) **de ajuda.**

In [ ]:
# criando matriz 2x2 com valores aleatórios
matriz_aleatoria = np.random.rand(2,2)
matriz_aleatoria

array([[0.85593525, 0.24420656],
       [0.98425316, 0.96212439]])

In [ ]:
# criando novamente a matriz 2x2 com valores aleatórios
matriz_aleatoria = np.random.rand(2,2)
matriz_aleatoria

array([[0.59139736, 0.7904624 ],
       [0.45602361, 0.69486158]])

In [ ]:
# criando matriz 2x2 com valores aleatórios com um seed
np.random.seed(0)
matriz_aleatoria = np.random.rand(2,2)
matriz_aleatoria

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [ ]:
# criando novamente a matriz 2x2 com valores aleatórios com um seed
np.random.seed(0)
matriz_aleatoria = np.random.rand(2,2)
matriz_aleatoria

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [ ]:
# criando uma série com uma distribuição de probabilidade normal
series_normal = np.random.normal(loc = 1, scale = 5, size=(12,1))
series_normal

array([[-0.79445027],
       [-1.61541995],
       [ 3.15976837],
       [ 5.74218634],
       [ 3.79212485],
       [ 1.5922023 ],
       [-4.93617403],
       [-1.86539517],
       [-3.5937559 ],
       [-1.29992917],
       [-0.54593449],
       [ 1.44196605]])

In [ ]:
# integração com o pandas
df_normal = pd.DataFrame(data = series_normal, columns = ['Dist. Normal'])
df_normal

Dist. Normal
0      -0.794450
1      -1.615420
2       3.159768
3       5.742186
4       3.792125
5       1.592202
6      -4.936174
7      -1.865395
8      -3.593756
9      -1.299929
10     -0.545934
11      1.441966

In [ ]:
df_normal.to_numpy()

array([[-0.79445027],
       [-1.61541995],
       [ 3.15976837],
       [ 5.74218634],
       [ 3.79212485],
       [ 1.5922023 ],
       [-4.93617403],
       [-1.86539517],
       [-3.5937559 ],
       [-1.29992917],
       [-0.54593449],
       [ 1.44196605]])

#### Operações matemáticas

In [ ]:
# criando duas matrizes
matriz_1 = np.array([[1,2],[3,4]], dtype=np.float64)
matriz_2 = np.array([[5,6],[7,8]], dtype=np.float64)

print('Matriz 1: \n', matriz_1)
print('\nMatriz 2: \n',matriz_2)

Matriz 1: 
 [[1. 2.]
 [3. 4.]]

Matriz 2: 
 [[5. 6.]
 [7. 8.]]


In [ ]:
# somando as matrizes
matriz_soma = np.add(matriz_1 , matriz_2)
matriz_soma

array([[ 6.,  8.],
       [10., 12.]])

In [ ]:
# subtraindo as matrizes
matriz_sub = np.subtract(matriz_1 , matriz_2)
matriz_sub

array([[-4., -4.],
       [-4., -4.]])

In [ ]:
# multiplicando os elementos das matrizes
matriz_mult = np.multiply(matriz_1 , matriz_2)
matriz_mult

array([[ 5., 12.],
       [21., 32.]])

In [ ]:
# dividindo os elementos das matrizes
matriz_div = np.divide(matriz_1 , matriz_2)
matriz_div

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
# multiplicando as matrizes (2x2) x (2x2)
matriz_dot = np.dot(matriz_1 , matriz_2)
matriz_dot

array([[19., 22.],
       [43., 50.]])

In [ ]:
# multiplicando as matrizes (2x2) x (2x1)
matriz_linha = np.array([1, 2])
vetor = matriz_linha.reshape(2,1)
matriz_dot_2x1 = np.dot(matriz_1 , vetor)
matriz_dot_2x1

array([[ 5.],
       [11.]])

In [ ]:
# multiplicação contrária
np.dot(vetor , matriz_1)

ValueError: ignored

In [ ]:
# operações dentro da matriz
matriz = np.array([[1,2],[3,4]])
matriz

array([[1, 2],
       [3, 4]])

In [ ]:
# somando todos os elementos
np.sum(matriz)

10

In [ ]:
# somando as linhas
np.sum(matriz, axis=0)

array([4, 6])

In [ ]:
# somando as colunas
np.sum(matriz, axis=1) 

array([3, 7])

#### Trasposta, inversa e solução de equações

In [ ]:
# observando o objeto matriz
matriz

array([[1, 2],
       [3, 4]])

In [ ]:
# obtendo a transposta
matriz.T

array([[1, 3],
       [2, 4]])

In [ ]:
# obtendo a inversa
np.linalg.inv(matriz)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Resolvendo o sistema de equações:

\begin{equation}
3x_{0} + x_{1} = 9 \\
x_{0} + 2x_{1} = 8
\end{equation}

In [ ]:
# criando a matriz das equações
equacoes = np.array([[3, 1], [1, 2]])
equacoes

array([[3, 1],
       [1, 2]])

In [ ]:
# criando o vetor das igualdades
igualdade = np.array([[9], [8]])
igualdade

array([[9],
       [8]])

In [ ]:
# obtendo x0 e x1
solucao = np.linalg.solve(equacoes, igualdade)
solucao

array([[2.],
       [3.]])

In [ ]:
# checando o resultado
np.dot(equacoes, solucao)

array([[9.],
       [8.]])

---

### Pacote sidrapy

O pacote `sidrapy` disponibiliza uma interface de consulta aos dados da API do Sidra, disponibilizado pelo IBGE. Basicamente, a função implementada no pacote envia uma requisição a API do Sidra, que coleta e envia os dados que foram requisitados.

O IBGE disponibiliza dois links muito úteis em caso de dúvidas.
 * [Link 1](http://api.sidra.ibge.gov.br/home/ajuda).
 * [Link 2](http://api.sidra.ibge.gov.br/).

No primeiro link é possível obter exemplos de como fazer a requisição por meio da API e no segundo link é possível obter os parâmetros necessários de acordo com a tabela que se deseja pesquisar.

Antes de usar o pacote sidrapy é necessário instalá-lo e posteriormente importá-lo.

In [ ]:
# instalação e importação do sidrapy
!pip install sidrapy 

In [ ]:
# importação do pacote
import sidrapy

Como exemplo, vamos coletar as informações do Índice Nacional de Preços ao consumidor Amplo, IPCA. 

O primeiro passo é saber o número da tabela. Para isso, basta acessar o site do Sidra ([link](https://sidra.ibge.gov.br/home/ipca/brasil)) e selecionar **IPCA** e depois selecionar o ícone de listas, conforma a imagem abaixo.

<img src = 'https://www.dropbox.com/s/s7v2wotfb3xwk8s/sidra1.png?dl=1'>


Ao fazer isso irá aparecer uma lista com as tabelas disponíveis, os respectivos números, nomes, períodos e territórios de abrangência.

<img src = 'https://www.dropbox.com/s/xpo43yfenepee06/sidra2.png?dl=1'>

Vamos utilizar como exemplo a tabela 7061 com os índices do IPCA dessazonalizado. Agora já com o número da tabela, devemos acessar o site de consulta da API do Sidra ([link 2](http://api.sidra.ibge.gov.br/)) para obtermos os parâmetros dessa série em particular, conforma mostra a imagem abaixo.

<img src = 'https://www.dropbox.com/s/a6p2k7zl9ayy9a3/sidra3.png?dl=1'>

Após clicar em **"Descrever"**, abre-se uma página com os parâmetros da tabela pesquisada.

<img src = 'https://www.dropbox.com/s/ggedpkhicxsf84i/sidra4.png?dl=1'>

São esses parâmetros que devemos passar na função do pacote sidrapy!

Como primeiro exemplo, vamos obter os índices gerais da variação mensal (%) do IPCA dessazonalizado. Então de acordo com a figura acima devemos passar os seguintes parâmetros na função **get_table** do pacote sidrapy:
  * Tabela: **7061**.
  * Variável: **306**.
  * Geral, grupo, subgrupo, item e subitem (315): **7169**.





In [ ]:
# obtendo os índices
ipca = sidrapy.get_table(table_code='7061', variable='306',classification='315/7169')

TypeError: ignored

De acordo com a mensagem de erro é necessário passar mais dois parâmetros na função: **territorial_level** e **ibge_territorial_code**. Essas duas informações podem ser também obtidas na página com os parâmetros, exibida acima. Essas informações podem ser visualizadas em 'Níveis Territoriais', conforme mostra a imagem abaixo:

<img src = 'https://www.dropbox.com/s/b2hcn4xj7ml3ur1/sidra5.png?dl=1'>

De acordo como a figura, para a tabela 7061 temos três níveis territorias (*territorial_level*): Brasil, Região Metropolitana e  Município. Para o nível territorial Brasil temos uma unidade territorial (*ibge_territorial_code*), para o nível territorial Região Metropolitana temos 10 unidades territoriais e, por fim, no nível territorial Municípios temos 6 unidades territoriais.

Nesse exemplo, queremos somente o valor do IPCA para o nível territoral Brasil, ou seja *territorial_level* igual a 1. Para sabermos o código da unidade territorial (*ibge_territorial_code*) dessa única unidade para o Brasil, temos que clicar na opção **"Listar unidades territoriais"**. Ao clicar uma nova janela irá aparecer, de acordo com a figura abaixo.

<img src = 'https://www.dropbox.com/s/fesow5z9r5o79wd/sidra6.png?dl=1'>

Então para o nível territorial Brasil temos a unidade territorial Brasil com o código igual a 1. Logo, devemos passar os seguintes parâmetros na função `get_table`.

  * Tabela: **7061**.
  * Variável: **306**.
  * Geral, grupo, subgrupo, item e subitem (315): **7169**.
  * Nível territorial: **1**.
  * Unidade territorial: **1**.







In [ ]:
# obtendo os índices
ipca = sidrapy.get_table(table_code='7061', variable='306',classification='315/7169', territorial_level='1', ibge_territorial_code='1')

In [ ]:
# observando o novo objeto
ipca

NC                 NN  ...                 MN      V
0  Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                           1             Brasil  ...                  %   0.31

[2 rows x 13 columns]

De acordo com o objeto acima, a variação mensal do índice geral do IPCA dessazonalizado para o Brasil em junho de 2020 foi 0.31%.

Por default, a API do IBGE retorna o último valor publicado. Mas é possível obter outros períodos por meio do parâmetro `period`. Por exemplo, se quisermos todos os períodos disponíveis basta definir o parâmetro igual a *'all'*.

In [ ]:
# obtendo os índices
ipca_all = sidrapy.get_table(table_code='7061', variable='306',classification='315/7169', territorial_level='1', ibge_territorial_code='1',
                         period = 'all')

In [ ]:
# observando o novo objeto
ipca_all

NC                 NN  ...                 MN      V
0  Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                           1             Brasil  ...                  %   0.15
2                           1             Brasil  ...                  %   0.26
3                           1             Brasil  ...                  %   0.01
4                           1             Brasil  ...                  %  -0.35
5                           1             Brasil  ...                  %  -0.36
6                           1             Brasil  ...                  %   0.31

[7 rows x 13 columns]

Se quisermos um período específico, basta definir o parâmetro `period` igual ao ano e mês em questão. Por exemplo, se quisermos o IPCA de abril de 2020, deve-se definir o parâmetro como sendo igual a *'202004'*.

In [ ]:
# obtendo os índices
ipca_abril = sidrapy.get_table(table_code='7061', variable='306',classification='315/7169', territorial_level='1', ibge_territorial_code='1',
                         period = '202004')

In [ ]:
# observando o objeto
ipca_abril

NC                 NN  ...                 MN      V
0  Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                           1             Brasil  ...                  %  -0.35

[2 rows x 13 columns]

Se quisermos as informações agora para o nível territorial de região metropolitana, devemos alterar o parâmetro `territorial_level` para **7** (conforme imagem anterior). Se quisermos o valor para todas as unidades territoriais, podemos definir o parâmetro `ibge_territorial_code` como sendo igual a *'all'*.

In [ ]:
# obtendo os índices
ipca_rm = sidrapy.get_table(table_code='7061', variable='306',classification='315/7169', territorial_level='7', ibge_territorial_code='all')
ipca_rm

NC                    NN  ...                 MN      V
0   Nível Territorial (Código)     Nível Territorial  ...  Unidade de Medida  Valor
1                            7  Região Metropolitana  ...                  %  -0.01
2                            7  Região Metropolitana  ...                  %   0.40
3                            7  Região Metropolitana  ...                  %   6.07
4                            7  Região Metropolitana  ...                  %   0.78
5                            7  Região Metropolitana  ...                  %   0.11
6                            7  Região Metropolitana  ...                  %   0.54
7                            7  Região Metropolitana  ...                  %   0.03
8                            7  Região Metropolitana  ...                  %   0.34
9                            7  Região Metropolitana  ...                  %   0.84
10                           7  Região Metropolitana  ...                  %  -0.01

[11 rows x 13 columns]

Mas se quisermos somente os índices para as regiões metropolitanas de Belo Horizonte (MG) e São Paulo (SP), podemos definir o parâmetro `ibge_territorial_code` como sendo igual a 3101 (código de BH) e 3501 (código de SP) da seguinte forma *'3101,3501'*. 

Esses códigos podem ser observados no objeto anterior, mas caso seja necessário, basta clicar em **Listas unidades territoriais** para a região metropolitana.

<img src = 'https://www.dropbox.com/s/b2hcn4xj7ml3ur1/sidra5.png?dl=1'>

Una nova janela com os códigos irá aparecer.

<img src = 'https://www.dropbox.com/s/n7kaclvb8sai2y1/sidra7.png?dl=1'>

In [ ]:
# obtendo os índices
ipca_mg_sp = sidrapy.get_table(table_code='7061', variable='306',classification='315/7169', territorial_level='7', ibge_territorial_code='3101,3501')
ipca_mg_sp

NC                    NN  ...                 MN      V
0  Nível Territorial (Código)     Nível Territorial  ...  Unidade de Medida  Valor
1                           7  Região Metropolitana  ...                  %   0.11
2                           7  Região Metropolitana  ...                  %   0.34

[3 rows x 13 columns]

Podemos também ao invés de obter o índice geral, obter o IPCA para bens desagregados, como por exemplo para arroz e feijão. Podemos observar na imagem abaixo os códigos.

<img src = 'https://www.dropbox.com/s/ggedpkhicxsf84i/sidra4.png?dl=1'>

Então no parâmetro `classification` devemos passar os códigos:
  * Arroz: **7173**.
  * Feijão - mulatinho: **7175**.
  * Feijão - preto: **7176**.
  * Feijão - macáçar (fradinho): **47617**.
  * Feijão - carioca (rajado): **12222**.

In [ ]:
# obtendo os índices
ipca_arroz_feijao = sidrapy.get_table(table_code='7061', variable='306',classification='315/7173,7175,7176,47617,12222', 
                                      territorial_level='1', ibge_territorial_code='1')
ipca_arroz_feijao

NC                 NN  ...                 MN      V
0  Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                           1             Brasil  ...                  %   2.56
2                           1             Brasil  ...                  %   5.82
3                           1             Brasil  ...                  %   6.75
4                           1             Brasil  ...                  %   2.88
5                           1             Brasil  ...                  %   5.08

[6 rows x 13 columns]

Para esses mesmos bens, pode ser mais interessante ao invés da variação mensal, usar o acumulado no ano. Segundo a imagem abaixo, o código para o IPCA dessazonalizado acumulado no ano é igual a *307*. Então basta utilizar esse código no parâmetro `variable`.

<img src = 'https://www.dropbox.com/s/ggedpkhicxsf84i/sidra4.png?dl=1'>

In [ ]:
# obtendo os índices
ipca_arroz_feijao_acumulado = sidrapy.get_table(table_code='7061', variable='307',classification='315/7173,7175,7176,47617,12222', 
                                      territorial_level='1', ibge_territorial_code='1')
ipca_arroz_feijao_acumulado

NC                 NN  ...                 MN      V
0  Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                           1             Brasil  ...                  %  15.99
2                           1             Brasil  ...                  %  18.52
3                           1             Brasil  ...                  %  27.92
4                           1             Brasil  ...                  %  28.10
5                           1             Brasil  ...                  %  22.77

[6 rows x 13 columns]

O exemplo utilizado aqui foi para a tabela 7061. Mas a identificação dos parâmetros e códigos é a mesma para qualquer tabela. 

---

#### Exercícios

Importar as seguintes tabelas:
  * Variação mensal do IPCA dessazonalizado para o município de Brasília (último valor publicado).
  * Série histórica do IPCA dessazonalizado com a variação mensal, a partir de janeiro/1998.
  * Variação acumulada no ano para 2019 do IPCA.
  * População (mil pessoas) por cor ou raça a partir da PNADC trimestral para o último período.
  * População (mil pessoas) por cor ou raça a partir da PNADC trimestral para todo período.
  * População (mil pessoas) por cor ou raça a partir da PNADC trimestral para o último período em Belo Horizonte/MG.
  * Percentual da população branca e preta a partir da PNADC trimestral para todo o período em Belo Horizonte/MG.

In [ ]:
# Variação mensal do IPCA dessazonalizado para o município de Brasília (último valor publicado)
ipca_brasilia = sidrapy.get_table(table_code='7061', variable='306',classification='315/7169', 
                                      territorial_level='6', ibge_territorial_code='5300108')
ipca_brasilia

NC                 NN  ...                 MN      V
0  Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                           6          Município  ...                  %   0.51

[2 rows x 13 columns]

In [ ]:
# Série histórica do IPCA dessazonalizado com a variação mensal, a partir de janeiro/1998
ipca_serie_historica = sidrapy.get_table(table_code='118', variable='306', 
                                      territorial_level='1', ibge_territorial_code='1', period = 'all')
ipca_serie_historica

NC                 NN  ...                 MN      V
0    Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                             1             Brasil  ...                  %   0.59
2                             1             Brasil  ...                  %   0.44
3                             1             Brasil  ...                  %   0.28
4                             1             Brasil  ...                  %   0.17
..                          ...                ...  ...                ...    ...
266                           1             Brasil  ...                  %   0.26
267                           1             Brasil  ...                  %   0.01
268                           1             Brasil  ...                  %  -0.35
269                           1             Brasil  ...                  %  -0.36
270                           1             Brasil  ...                  %   0.31

[271 rows x 11 columns]

In [ ]:
# Variação acumulada no ano para 2019 do IPCA.
ipca_acumulado_2019 = sidrapy.get_table(table_code='1737', variable='69', 
                                      territorial_level='1', ibge_territorial_code='1', period = '201901-201912')
ipca_acumulado_2019

NC                 NN  ...                 MN      V
0   Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                            1             Brasil  ...                  %   0.32
2                            1             Brasil  ...                  %   0.75
3                            1             Brasil  ...                  %   1.51
4                            1             Brasil  ...                  %   2.09
5                            1             Brasil  ...                  %   2.22
6                            1             Brasil  ...                  %   2.23
7                            1             Brasil  ...                  %   2.42
8                            1             Brasil  ...                  %   2.54
9                            1             Brasil  ...                  %   2.49
10                           1             Brasil  ...                  %   2.60
11                           1             Brasil  ...                  %   3.12
12                           1             Brasil  ...                  %   4.31

[13 rows x 11 columns]

In [ ]:
# População (mil pessoas) por cor ou raça a partir da PNADC trimestral para o último período
populacao = sidrapy.get_table(table_code='6403', variable='606',classification='86/2776,2777,2779', 
                                      territorial_level='1', ibge_territorial_code='1')
populacao

NC                 NN  ...                 MN      V
0  Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                           1             Brasil  ...        Mil pessoas  89856
2                           1             Brasil  ...        Mil pessoas  19339
3                           1             Brasil  ...        Mil pessoas  99257

[4 rows x 13 columns]

In [ ]:
# População (mil pessoas) por cor ou raça a partir da PNADC trimestral para todo período
populacao_all = sidrapy.get_table(table_code='6403', variable='606',classification='86/2776,2777,2779', 
                                      territorial_level='1', ibge_territorial_code='1', period = 'all')
populacao_all

NC                 NN  ...                 MN      V
0   Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                            1             Brasil  ...        Mil pessoas  92773
2                            1             Brasil  ...        Mil pessoas  14866
3                            1             Brasil  ...        Mil pessoas  87909
4                            1             Brasil  ...        Mil pessoas  91715
..                         ...                ...  ...                ...    ...
95                           1             Brasil  ...        Mil pessoas  19880
96                           1             Brasil  ...        Mil pessoas  99355
97                           1             Brasil  ...        Mil pessoas  89856
98                           1             Brasil  ...        Mil pessoas  19339
99                           1             Brasil  ...        Mil pessoas  99257

[100 rows x 13 columns]

In [ ]:
# População (mil pessoas) por cor ou raça a partir da PNADC trimestral para o último período em Belo Horizonte/MG
populacao_bh = sidrapy.get_table(table_code='6403', variable='606',classification='86/2776,2777,2779', 
                                      territorial_level='6', ibge_territorial_code='3106200')
populacao_bh


NC                 NN  ...                 MN      V
0  Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                           6          Município  ...        Mil pessoas   1044
2                           6          Município  ...        Mil pessoas    335
3                           6          Município  ...        Mil pessoas   1130

[4 rows x 13 columns]

In [ ]:
# Percentual da população branca e preta a partir da PNADC trimestral para todo o período em Belo Horizonte/MG
populacao_bh_percentual = sidrapy.get_table(table_code='6403', variable='608',classification='86/2776,2777', 
                                      territorial_level='6', ibge_territorial_code='3106200')
populacao_bh_percentual

NC                 NN  ...                 MN      V
0  Nível Territorial (Código)  Nível Territorial  ...  Unidade de Medida  Valor
1                           6          Município  ...                  %   41.5
2                           6          Município  ...                  %   13.3

[3 rows x 13 columns]

---